"""Static 69-file section map for the FC/FK factory service manual."""

SECTIONS: dict[str, str] = {
    "SM_1": "Safety / General Information",
    "SM_2": "Maintenance Minder",
    "SM_3": "DTC Troubleshooting",
    "SM_4": "DTC Advanced Diagnostics",
    "SM_5": "Engine",
    "SM_6": "Cooling",
    "SM_7": "Engine Lubrication",
    "SM_8": "A/F Sensor",
    "SM_9": "Turbocharger Control",
    "SM_10": "Fuel and Emissions",
    "SM_11": "Fuel Supply",
    "SM_12": "PGM-FI",
    "SM_13": "Catalytic Converter",
    "SM_14": "PCV",
    "SM_15": "Electronic Throttle Control",
    "SM_16": "Intake and Exhaust",
    "SM_17": "Starter",
    "SM_18": "EVAP",
    "SM_19": "Ignition",
    "SM_20": "Cruise Control",
    "SM_21": "Charging",
    "SM_22": "12 Volt Battery",
    "SM_23": "Clutch",
    "SM_24": "Manual Transmission",
    "SM_25": "CVT",
    "SM_26": "TCM Connectors",
    "SM_27": "Brakes",
    "SM_28": "Electric Parking Brake",
    "SM_29": "VSA",
    "SM_30": "Driveline / Axle",
    "SM_31": "Suspension",
    "SM_32": "Adaptive Damper",
    "SM_33": "Front Stopper Link",
    "SM_34": "TPMS",
    "SM_35": "EPS",
    "SM_36": "Steering",
    "SM_37": "Climate Control",
    "SM_38": "A/C Service",
    "SM_39": "Audio",
    "SM_40": "Navigation",
    "SM_41": "Network Communications",
    "SM_42": "Driving Support",
    "SM_43": "LKAS",
    "SM_44": "Keyless Access",
    "SM_45": "Immobilizer",
    "SM_46": "Interior Trim",
    "SM_47": "Dashboard",
    "SM_48": "Power Mirrors",
    "SM_49": "Gauges",
    "SM_50": "Horns",
    "SM_51": "Power Windows",
    "SM_52": "Seats",
    "SM_53": "Seat Belts",
    "SM_54": "SRS",
    "SM_55": "Moonroof",
    "SM_56": "Ambient Light",
    "SM_57": "Exterior Trim",
    "SM_58": "Glass",
    "SM_59": "Bumpers",
    "SM_60": "Front Door",
    "SM_61": "Tailgate",
    "SM_62": "Hood",
    "SM_63": "Wipers / Washers",
    "SM_64": "Body Repair / Aluminum",
    "SM_65": "General Information (Body)",
    "SM_66": "BCM Connectors",
    "SM_67": "Accessory Power Sockets",
    "SM_68": "Wire Harness and Grounds",
    "SM_69": "Wiring Diagrams",
}

MVP_DOC_IDS = ("SM_2", "SM_22", "SM_27")
DAMAGED_DOC_IDS = ("SM_58", "SM_63", "SM_64", "SM_67")


def doc_id_from_filename(filename: str) -> str:
    return filename.rsplit(".", 1)[0]
